# Generated by Django 4.2.2 on 2023-06-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Home insurance'), ('car', 'Car insurance'), ('property', 'Property insurance')], max_length=32)),
                ('subject', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('insurer', 'Insurer'), ('insured', 'Insured')], max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.insurance')),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.insured'),
        ),
    ]
