# Generated by Django 4.1.1 on 2023-06-26 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('insurer', 'Insurer'), ('insured', 'Insured')], max_length=10, null=True)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(max_length=16)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insured', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('insured', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.insured')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Home insurance'), ('car', 'Car insurance'), ('property', 'Property insurance')], max_length=32)),
                ('subject', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('insurance', models.ManyToManyField(related_name='insurance', to='evidence.insured')),
            ],
        ),
    ]
