# Generated by Django 4.1.1 on 2023-06-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='user',
        ),
    ]
