# Generated by Django 4.1.1 on 2023-06-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='insured',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='insuranceevent',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.insurance'),
        ),
    ]
