# Generated by Django 4.1.1 on 2023-06-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0002_remove_insuranceevent_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insured', to=settings.AUTH_USER_MODEL),
        ),
    ]
