# Generated by Django 4.1.1 on 2023-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_insurance_options_alter_insured_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceevent',
            name='subject',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
