# Generated by Django 4.1.1 on 2023-06-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_remove_insured_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceevent',
            name='insured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.insured'),
        ),
    ]
