# Generated by Django 4.1.1 on 2023-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_insured_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurance',
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance',
            field=models.ManyToManyField(related_name='insurance', to='evidence.insured'),
        ),
    ]
