# Generated by Django 4.1.1 on 2023-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_insuranceevent_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceevent',
            name='insured',
        ),
    ]
