# Generated by Django 4.1.1 on 2023-06-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_insured_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceevent',
            name='insurance',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='evidence.insured'),
        ),
    ]
