# Generated by Django 4.1.1 on 2023-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_remove_insuranceevent_insured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='zipcode',
            field=models.CharField(max_length=16),
        ),
    ]
