# Generated by Django 4.1.1 on 2023-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_remove_insuranceevent_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
