# Generated by Django 4.1.1 on 2023-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_alter_insured_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='amount',
            field=models.CharField(max_length=32),
        ),
    ]
