# Generated by Django 4.1.1 on 2023-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_alter_insurance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='is_policyholder',
            field=models.BooleanField(default=False),
        ),
    ]
