# Generated by Django 4.1.1 on 2023-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_insured_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='role',
            field=models.CharField(choices=[('insurer', 'Insurer'), ('insured', 'Insured')], max_length=10),
        ),
    ]
