# Generated by Django 4.1.1 on 2023-07-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_insured_is_policyholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='is_policyholder',
        ),
    ]
