# Generated by Django 4.1.1 on 2023-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0008_remove_insured_is_policyholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='is_policyholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insured',
            name='role',
            field=models.CharField(choices=[('insurer', 'INSURER'), ('insured', 'INSURED')], max_length=10, null=True),
        ),
    ]
