# Generated by Django 4.1.1 on 2023-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0009_insured_is_policyholder_alter_insured_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='role',
            field=models.CharField(choices=[('insurer', 'Policyholder'), ('insured', 'Insured')], max_length=10, null=True),
        ),
    ]
