# Generated by Django 4.1.1 on 2023-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0010_alter_insured_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='role',
            field=models.CharField(choices=[('policyholder', 'Policyholder'), ('insured', 'Insured')], max_length=20, null=True),
        ),
    ]
