# Generated by Django 4.1.1 on 2023-07-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0011_alter_insured_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insured',
            name='role',
            field=models.CharField(choices=[('insurer', 'Policyholder'), ('insured', 'Insured')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insured',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insured', to=settings.AUTH_USER_MODEL),
        ),
    ]
