# Generated by Django 4.1.1 on 2023-07-25 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0012_alter_insurance_amount_alter_insured_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceevent',
            old_name='date',
            new_name='date_submitted',
        ),
        migrations.AddField(
            model_name='insuranceevent',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insuranceevent',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceevent',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='event_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='insuranceevent',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.insured'),
        ),
    ]
