# Generated by Django 4.1.1 on 2023-07-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0013_rename_date_insuranceevent_date_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceevent',
            old_name='cost',
            new_name='paid_out',
        ),
    ]
