# Generated by Django 4.1.1 on 2023-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0016_remove_insuranceevent_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceevent',
            name='submitted_by',
        ),
    ]
