# Generated by Django 4.1.1 on 2023-07-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0017_remove_insuranceevent_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceevent',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.insured'),
        ),
    ]
