# Generated by Django 4.1.1 on 2023-07-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0018_insuranceevent_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceevent',
            name='submitted_by',
        ),
    ]
