# Generated by Django 4.1.1 on 2023-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0019_remove_insuranceevent_submitted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceevent',
            old_name='paid_out',
            new_name='total_payout',
        ),
        migrations.RemoveField(
            model_name='insuranceevent',
            name='report',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('events', models.ManyToManyField(related_name='reports', to='evidence.insuranceevent')),
            ],
        ),
    ]
