# Generated by Django 4.1.1 on 2023-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0020_rename_paid_out_insuranceevent_total_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=32),
        ),
    ]
